### PR TITLE
m1721: backport lzo-rle from linux mainline

### PR DESCRIPTION
**Pull request by urain39**
This PR picked lzo-rle related commits from linux mainline, and fixed conflicts<del>, but haven't tested yet</del>.

### CODE REVIEW

**Comment by tdrkDev** [comment]
Please test and I'll think about merge

**Comment by urain39** [comment]
In my testings it can boot, but it will reboot after about 5 seconds. And my problem is how can i get the kmsg before reboot, can you help me?

**Comment by tdrkDev** [comment]
before - you can't, after - pull /sys/fs/pstore/console-ramoops-0 from recovery

**Comment by urain39** [comment]
Thanks!

**Comment by urain39** [comment]
Thanks!

**Comment by urain39** [comment]
It seems all right, ready to review :)

**Review by urain39 — COMMENTED** [review]
kvmalloc backport from https://patchwork.kernel.org/project/backports/patch/20180906065750.89673-2-nbd@nbd.name/

Should we notice in source code?

**Comment by tdrkDev** [comment]
You can remove kvmalloc implementation, I am doing backport of this API in linux/mm.h on sapphire-erofs-op7-with-vbswap branch

**Comment by urain39** [comment]
Also should i revert https://github.com/meizucustoms/android_kernel_meizu_m1721/pull/4/commits/8a5f17e06d470d8619a2aebd4d8f4fb8d32c1876? Because it looks like zRAM cannot work with zSwap (vbSwap)...

<details>
  <summary>dmesg-ramoops-0</summary>
  <pre><code>
Oops#1 Part1
<6>[   65.265354] gf: gf_ioctl: GF_IOC_DISABLE_SPI_CLK
<6>[   65.265355] gf: gf_ioctl: Doesn't support control clock.
<6>[   65.265581] gf: gf_ioctl: command: 0x40046705
<6>[   65.265584] gf: gf_ioctl: GF_IOC_ENABLE_SPI_CLK
<6>[   65.265585] gf: gf_ioctl: Doesn't support control clock.
<6>[   65.279909] gf: gf_ioctl: command: 0x6706
<6>[   65.279915] gf: gf_ioctl: GF_IOC_DISABLE_SPI_CLK
<6>[   65.279916] gf: gf_ioctl: Doesn't support control clock.
<6>[   65.280108] gf: gf_ioctl: command: 0x6704
<6>[   65.280112] gf: gf_ioctl: GF_IOC_DISABLE_IRQ
<6>[   65.280116] gf: gf_ioctl: command: 0x6701
<6>[   65.280118] gf: gf_ioctl: GF_IOC_EXIT
<6>[   65.280155] gf: gf_ioctl: command: 0x40046705
<6>[   65.280157] gf: gf_ioctl: GF_IOC_ENABLE_SPI_CLK
<6>[   65.280158] gf: gf_ioctl: Doesn't support control clock.
<6>[   65.286417] gf: gf_ioctl: command: 0x6706
<6>[   65.286421] gf: gf_ioctl: GF_IOC_DISABLE_SPI_CLK
<6>[   65.286423] gf: gf_ioctl: Doesn't support control clock.
<4>[   65.290304] QSEECOM: __qseecom_unload_app: App (196610) is unloaded
<6>[   65.295366] gf: gf_release: disable IRQ. IRQ = 282
<6>[   65.295380] gf: gf_hw_reset_low: low reset done.
<6>[   65.306061] gf: gf_power_off: powered off.
<38>[   65.416932] type=1400 audit(1655815376.247:1242): avc: denied { getattr } for comm="Binder:2176_2" scontext=u:r:system_server:s0 tcontext=u:r:surfaceflinger:s0 tclass=process permissive=1
<6>[   65.433589] binder: 4219:4219 ioctl 40046210 7ff8b3d1c4 returned -22
<6>[   65.759940] binder: 4267:4267 ioctl 40046210 7ff8b3d1c4 returned -22
<38>[   65.838660] type=1400 audit(1655815376.669:1243): avc: denied { getattr } for comm="Binder:441_4" scontext=u:r:vold:s0 tcontext=u:r:system_server:s0 tclass=process permissive=1
<11>[   65.861382] init: Control message: Could not find 'android.hardware.biometrics.fingerprint@2.1::IBiometricsFingerprint/default' for ctl.interface_start from pid: 439 (/system/bin/hwservicemanager)
<3>[   66.054689] msm_mi2s_snd_startup(): substream = subdevice #0  stream = 0
<3>[   66.059670] q6core_send_get_avcs_fwk_ver_cmd: DSP returned error[ADSP_EUNSUPPORTED]
<38>[   66.120600] type=1400 audit(1655815376.951:1244): avc: denied { read } for comm="Binder:1477_2" scontext=u:r:installd:s0 tcontext=u:r:system_server:s0 tclass=file permissive=1
<38>[   66.120794] type=1400 audit(1655815376.951:1245): avc: denied { search } for comm="Binder:1477_2" name="2176" dev="proc" ino=40203 scontext=u:r:installd:s0 tcontext=u:r:system_server:s0 tclass=dir permissive=1
<38>[   66.120869] type=1400 audit(1655815376.951:1246): avc: denied { open } for comm="Binder:1477_2" path="/proc/2176/attr/current" dev="proc" ino=43160 scontext=u:r:installd:s0 tcontext=u:r:system_server:s0 tclass=file permissive=1
<38>[   66.120919] type=1400 audit(1655815376.951:1247): avc: denied { getattr } for comm="Binder:1477_2" scontext=u:r:installd:s0 tcontext=u:r:system_server:s0 tclass=process permissive=1
<4>[   66.120993] ------------[ cut here ]------------
<2>[   66.120996] kernel BUG at mm/zswap.c:967!
<4>[   66.121018] ------------[ cut here ]------------
<2>[   66.121023] kernel BUG at mm/zswap.c:967!
<0>[   66.121027] Internal error: Oops - BUG: 0 [#1] PREEMPT SMP
<4>[   66.121037] Modules linked in:
<4>[   66.121051] CPU: 0 PID: 2688 Comm: tencent.tim:MSF Not tainted 4.9.319-g89433ced6-dirty #7
<4>[   66.121055] Hardware name: Qualcomm Technologies, Inc. MSM8953 + PMI8950 QRD SKU3 (DT)
<4>[   66.121063] task: 000000008a9a3a93 task.stack: 000000000af8046b
<4>[   66.121077] PC is at zswap_frontswap_load+0x268/0x280
<4>[   66.121082] LR is at zswap_frontswap_load+0x178/0x280
<4>[   66.121086] pc : [<ffffff800822de98>] lr : [<ffffff800822dda8>] pstate: 40000145
<4>[   66.121089] sp : ffffffc0516a3a00
<4>[   66.121093] x29: ffffffc0516a3a00 x28: ffffffc05393e900 
<4>[   66.121100] x27: 0000000000000040 x26: 0000000070152fb0 
<4>[   66.121107] x25: ffffffc0259fac08 x24: ffffffc0386e3a00 
<4>[   66.121114] x23: ffffffc0259fac00 x22: ffffff80097267c0 
<4>[   66.121120] x21: ffffffc05393e900 x20: ffffffc024c08000 
<4>[   66.121127] x19: ffffffc0992f1a48 x18: 0000000000000000 
<4>[   66.121133] x17: 000018f500001a31 x16: 0000000000001010 
<4>[   66.121140] x15: 0000000000080001 x14: 0000000000000000 
<4>[   66.121147] x13: 000000007062aeac x12: 0000000070402ca8 
<4>[   66.121153] x11: 000000007013f648 x10: 000000006ff9c2b8 
<4>[   66.121159] x9 : 000000006ff1bdc0 x8 : 0000000000000000 
<4>[   66.121166] x7 : ffffffbf00145240 x6 : ffffffbf00000000 
<4>[   66.121173] x5 : 00000040a8192000 x4 : 0000000000145240 
<4>[   66.121179] x3 : 0000000000000001 x2 : 0000451490000000 
<4>[   66.121186] x1 : ffffffc05393e900 x0 : 0000000000400000 
<4>[   66.121196] 
<4>[   66.121196] PC: zswap_frontswap_load+0x228/0x280:
<4>[   66.121200] de58  37f80220 d5384101 b9404820 51000400 b9004820 35fffa00 f9400020 721f001f
<4>[   66.121220] de78  54fff9a0 943ceb89 17ffffcb aa1403e0 94098c16 17ffffba d4210000 17ffffbd
<4>[   66.121238] de98  d4210000 d4210000 17ffffef 97fa887f d503201f d503201f a9b87bfd 910003fd
<4>[   66.121256] deb8  a90153f3 b0010754 913ac294 91002283 a9025bf5 b000a7d6 911f02d6 a90363f7
<4>[   66.121278] 
<4>[   66.121278] LR: zswap_frontswap_load+0x138/0x280:
<4>[   66.121282] dd68  51000400 b9004aa0 340004e0 d5384101 b94ad020 51000400 b90ad020 37f80860
<4>[   66.121302] dd88  d5384101 b9404820 51000400 b9004820 34000300 a9428660 f9400000 940030b3
<4>[   66.121321] dda8  35000798 aa1903e0 943cfe28 aa1303e1 aa1703e0 97ffff59 aa1903e0 943cfe93
<4>[   66.121340] ddc8  52800000 f9402fe1 f94002c2 eb020021 d2800002 54000641 a94153f3 a9425bf5
<4>[   66.121360] 
<4>[   66.121360] SP: 0xffffffc0516a39c0:
<4>[   66.121364] 39c0  0822dda8 ffffff80 516a3a00 ffffffc0 0822de98 ffffff80 40000145 00000000
<4>[   66.121383] 39e0  516a39f0 ffffffc0 0823a084 ffffff80 ffffffff 0000007f 0822dda8 ffffff80
<4>[   66.121402] 3a00  516a3a60 ffffffc0 0822cbd0 ffffff80 386e3a00 ffffffc0 0a0093e8 ffffff80
<4>[   66.121420] 3a20  00930200 ffffffbf 00000001 00000000 0000b9ac 00000000 386e3a00 ffffffc0
<0>[   66.121440] Process tencent.tim:MSF (pid: 2688, stack limit = 0x000000000af8046b)
<4>[   66.121444] Call trace:
<4>[   66.121450] Exception stack(0xffffffc0516a37f0 to 0xffffffc0516a3920)
<4>[   66.121455] 37e0:                                   ffffffc0992f1a48 0000007fffffffff
<4>[   66.121460] 3800: ffffffc0516a3a00 ffffff800822de98 0000000040000145 000000000000003d
<4>[   66.121465] 3820: ffffffc0259fac08 0000000000000020 010000000000003e 0000000000040900
<4>[   66.121470] 3840: ffffffc0516a3890 ffffff80081e4cf0 ffffffc0516a3890 ffffff80081e4d4c
<4>[   66.121475] 3860: ffffff800a2b3600 0000000000000000 00000000000000c1 0000000000000000
<4>[   66.121479] 3880: ffffff800a2b2100 0000000000000000 ffffffc0516a3950 ffffff80081e5b40
<4>[   66.121484] 38a0: 00000000000000c1 ffffff800a2b2100 00000000024200ca 0000000000000000
<4>[   66.121489] 38c0: 0000000000000000 0000000000040900 0000000000400000 ffffffc05393e900
<4>[   66.121493] 38e0: 0000451490000000 0000000000000001 0000000000145240 00000040a8192000
<4>[   66.121498] 3900: ffffffbf00000000 ffffffbf00145240 0000000000000000 000000006ff1bdc0
<4>[   66.121504] [<00000000d7f2f8d6>] zswap_frontswap_load+0x268/0x280
<4>[   66.121510] [<00000000513112fd>] __frontswap_load+0x90/0x160
<4>[   66.121515] [<0000000057e018e9>] swap_readpage+0xb4/0x1f0
<4>[   66.121520] [<0000000000dd2e4f>] read_swap_cache_async+0x5c/0x70
<4>[   66.121524] [<00000000fcc1f438>] swapin_readahead+0x5c/0x240
<4>[   66.121531] [<00000000fb1fd263>] do_swap_page+0x32c/0x4d0
<4>[   66.121537] [<00000000e62f81e5>] handle_pte_fault+0x98/0xda0
<4>[   66.121542] [<00000000b4e6c24d>] __handle_speculative_fault+0x178/0x7f0
<4>[   66.121549] [<00000000118d9638>] do_page_fault+0x110/0x430
<4>[   66.121554] [<00000000870a0c4b>] do_translation_fault+0x3c/0x50
<4>[   66.121560] [<0000000068adfd70>] do_mem_abort+0x58/0xd0
<4>[   66.121564] Exception stack(0xffffffc0516a3e00 to 0xffffffc0516a3f30)
<4>[   66.121568] 3e00: 0000000000400000 00000040a8192000 ffffffffffffffff 00000000e869a4ca
<4>[   66.121574] 3e20: 00000000600f0030 ffffffc05393e900 0000000000000000 ffffff8009192140
<4>[   66.121579] 3e40: fffffffffffffe90 0000000000040900 ffffffc0516a3e70 ffffff800808c12c
<4>[   66.121584] 3e60: 0000000000400002 ffffffc05393e900 ffffffc0b1d4b080 ffffff8008083920
<4>[   66.121589] 3e80: ffffffc0516a3ec0 00000040a8192000 ffffffffffffffff 00000000e888bf7c
<4>[   66.121593] 3ea0: 00000000900f0030 0000000000000000 ffffffc0b1d470a0 0000000000040900
<4>[   66.121598] 3ec0: 0000000070152fa8 0000000000002966 0000000070152fac 0000000000000000
<4>[   66.121603] 3ee0: 0000000070152fa8 0000000012c16370 0000000000004940 0000000000002965
<4>[   66.121608] 3f00: 0000000000000070 00000000edf8c480 00000000b573b0b0 0000000070152fac
<4>[   66.121612] 3f20: 0000000000000000 00000000ffc43360
<4>[   66.121617] [<000000002363ed04>] el0_da+0x20/0x24
<0>[   66.121623] Code: 94098c16 17ffffba d4210000 17ffffbd (d4210000) 
<4>[   66.121628] ---[ end trace 385e79726a4a408f ]---
  </code></pre>
</details>

**Review by tdrkDev — CHANGES_REQUESTED** [review]
We already have VBSWAP (advanced zRAM by Samsung) enabled and it works even better than zRAM. If you want to use lzo-rle for memory compression, please port or enable it for vbswap/zswap.

**Comment by urain39** [comment]
It works in theory.

**Comment by tdrkDev** [comment]
Please leave only `CONFIG_CRYPTO_LZO=y` in defconfig and I'll test it :+1:

**Comment by urain39** [comment]
I noticed that vbswap/zswap can reset the compressor through /sys/module/zswap/parameters/compressor; Sometimes zstd might be better, so I added it.

**Comment by tdrkDev** [comment]
Hmm, you can add ZSTD in separate commit then, didn't know that. LZ4 is enabled by default as ZSWAP dependency. Also, please, rebase your changes, too many junk commits (revert xyz, remove xyz) :)
I'll test your changes in some hours, thanks! :1st_place_medal:

**Comment by tdrkDev** [comment]
I've done some tests, it works very good! With swappiness = 200, phone works even better than with lz4, thanks a lot. But, please, do rebase and only then I'll merge it to main branch)

**Comment by tdrkDev** [comment]
Looks good, I'll merge it after finishing EROFS, LMK and other changes on separate branch.

**Pull request merged**
